import samsungctl

config = {
    "host" : "192.168.0.19",
    "port" : 55000,
    "description" :"controle remoto da alexa",
    "method" : "legacy",
    "name" : "alexa",
    "id" : "777",
    "timeout" : 0,}

keys = {
    "poweroff key" :  "KEY_POWEROFF",
    "up key" : "KEY_UP",
    "down key" : "KEY_DOWN",
    "left key" : "KEY_LEFT",
    "right key" : "KEY_RIGHT",
    "channel up key" : "KEY_CHUP",
    "channel down key" : "KEY_CHDOWN",
    "enter key" : "KEY_ENTER",
    "return key" : "KEY_RETURN",
    "channel list key" : "KEY_CH_LIST",
    "menu key" : "KEY_MENU",
    "source key": "KEY_SOURCE",
    "guide key" : "KEY_GUIDE",
    "tools key" : "KEY_TOOLS",
    "info key" :"KEY_INFO",
    "red key" : "KEY_RED",
    "green_key" : "KEY_GREEN",
    "yellow key" : "KEY_YELLOW",
    "blue key key" : "KEY_BLUE",
    "3d key" : "KEY_PANNEL_CHDOWN",
    "volume up key" : "KEY_VOLUP",
    "volume down key" : "KEY_VOLDOWN",
    "mute key" : "KEY_MUTE",
    "0 key" : "KEY_0",
    "1 key" : "KEY_1",
    "2 key" : "KEY_2",
    "3 key" : "KEY_3",
    "4 key" : "KEY_4",
    "5 key" : "KEY_5",
    "6 key" : "KEY_6",
    "7 key" : "KEY_7",
    "8 key" : "KEY_8",
    "9 key" : "KEY_9",
    "source key" : "KEY_DTV",
    "hdmi key" : "KEY_HDMI",
    "smart hub key" : "KEY_CONTENTS",
}